// Code generated by MockGen. DO NOT EDIT.
// Source: client.go

// Package docker is a generated GoMock package.
package docker

import (
	context "context"
	dockerclient "github.com/docker/docker/client"
	contracts "github.com/estafette/estafette-ci-contracts"
	manifest "github.com/estafette/estafette-ci-manifest"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockClient is a mock of Client interface
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
}

// MockClientMockRecorder is the mock recorder for MockClient
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	return m.recorder
}

// IsImagePulled mocks base method
func (m *MockClient) IsImagePulled(stageName, containerImage string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsImagePulled", stageName, containerImage)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsImagePulled indicates an expected call of IsImagePulled
func (mr *MockClientMockRecorder) IsImagePulled(stageName, containerImage interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsImagePulled", reflect.TypeOf((*MockClient)(nil).IsImagePulled), stageName, containerImage)
}

// IsTrustedImage mocks base method
func (m *MockClient) IsTrustedImage(stageName, containerImage string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsTrustedImage", stageName, containerImage)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsTrustedImage indicates an expected call of IsTrustedImage
func (mr *MockClientMockRecorder) IsTrustedImage(stageName, containerImage interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsTrustedImage", reflect.TypeOf((*MockClient)(nil).IsTrustedImage), stageName, containerImage)
}

// HasInjectedCredentials mocks base method
func (m *MockClient) HasInjectedCredentials(stageName, containerImage string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasInjectedCredentials", stageName, containerImage)
	ret0, _ := ret[0].(bool)
	return ret0
}

// HasInjectedCredentials indicates an expected call of HasInjectedCredentials
func (mr *MockClientMockRecorder) HasInjectedCredentials(stageName, containerImage interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasInjectedCredentials", reflect.TypeOf((*MockClient)(nil).HasInjectedCredentials), stageName, containerImage)
}

// PullImage mocks base method
func (m *MockClient) PullImage(ctx context.Context, stageName, containerImage string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PullImage", ctx, stageName, containerImage)
	ret0, _ := ret[0].(error)
	return ret0
}

// PullImage indicates an expected call of PullImage
func (mr *MockClientMockRecorder) PullImage(ctx, stageName, containerImage interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PullImage", reflect.TypeOf((*MockClient)(nil).PullImage), ctx, stageName, containerImage)
}

// GetImageSize mocks base method
func (m *MockClient) GetImageSize(containerImage string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetImageSize", containerImage)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetImageSize indicates an expected call of GetImageSize
func (mr *MockClientMockRecorder) GetImageSize(containerImage interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetImageSize", reflect.TypeOf((*MockClient)(nil).GetImageSize), containerImage)
}

// StartStageContainer mocks base method
func (m *MockClient) StartStageContainer(ctx context.Context, depth, runIndex int, dir string, envvars map[string]string, stage manifest.EstafetteStage) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StartStageContainer", ctx, depth, runIndex, dir, envvars, stage)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StartStageContainer indicates an expected call of StartStageContainer
func (mr *MockClientMockRecorder) StartStageContainer(ctx, depth, runIndex, dir, envvars, stage interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartStageContainer", reflect.TypeOf((*MockClient)(nil).StartStageContainer), ctx, depth, runIndex, dir, envvars, stage)
}

// StartServiceContainer mocks base method
func (m *MockClient) StartServiceContainer(ctx context.Context, envvars map[string]string, service manifest.EstafetteService) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StartServiceContainer", ctx, envvars, service)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StartServiceContainer indicates an expected call of StartServiceContainer
func (mr *MockClientMockRecorder) StartServiceContainer(ctx, envvars, service interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartServiceContainer", reflect.TypeOf((*MockClient)(nil).StartServiceContainer), ctx, envvars, service)
}

// RunReadinessProbeContainer mocks base method
func (m *MockClient) RunReadinessProbeContainer(ctx context.Context, parentStage manifest.EstafetteStage, service manifest.EstafetteService, readiness manifest.ReadinessProbe) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RunReadinessProbeContainer", ctx, parentStage, service, readiness)
	ret0, _ := ret[0].(error)
	return ret0
}

// RunReadinessProbeContainer indicates an expected call of RunReadinessProbeContainer
func (mr *MockClientMockRecorder) RunReadinessProbeContainer(ctx, parentStage, service, readiness interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RunReadinessProbeContainer", reflect.TypeOf((*MockClient)(nil).RunReadinessProbeContainer), ctx, parentStage, service, readiness)
}

// TailContainerLogs mocks base method
func (m *MockClient) TailContainerLogs(ctx context.Context, containerID, parentStageName, stageName string, stageType contracts.LogType, depth, runIndex int, multiStage *bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TailContainerLogs", ctx, containerID, parentStageName, stageName, stageType, depth, runIndex, multiStage)
	ret0, _ := ret[0].(error)
	return ret0
}

// TailContainerLogs indicates an expected call of TailContainerLogs
func (mr *MockClientMockRecorder) TailContainerLogs(ctx, containerID, parentStageName, stageName, stageType, depth, runIndex, multiStage interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TailContainerLogs", reflect.TypeOf((*MockClient)(nil).TailContainerLogs), ctx, containerID, parentStageName, stageName, stageType, depth, runIndex, multiStage)
}

// StopSingleStageServiceContainers mocks base method
func (m *MockClient) StopSingleStageServiceContainers(ctx context.Context, parentStage manifest.EstafetteStage) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "StopSingleStageServiceContainers", ctx, parentStage)
}

// StopSingleStageServiceContainers indicates an expected call of StopSingleStageServiceContainers
func (mr *MockClientMockRecorder) StopSingleStageServiceContainers(ctx, parentStage interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StopSingleStageServiceContainers", reflect.TypeOf((*MockClient)(nil).StopSingleStageServiceContainers), ctx, parentStage)
}

// StopMultiStageServiceContainers mocks base method
func (m *MockClient) StopMultiStageServiceContainers(ctx context.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "StopMultiStageServiceContainers", ctx)
}

// StopMultiStageServiceContainers indicates an expected call of StopMultiStageServiceContainers
func (mr *MockClientMockRecorder) StopMultiStageServiceContainers(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StopMultiStageServiceContainers", reflect.TypeOf((*MockClient)(nil).StopMultiStageServiceContainers), ctx)
}

// StartDockerDaemon mocks base method
func (m *MockClient) StartDockerDaemon() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StartDockerDaemon")
	ret0, _ := ret[0].(error)
	return ret0
}

// StartDockerDaemon indicates an expected call of StartDockerDaemon
func (mr *MockClientMockRecorder) StartDockerDaemon() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartDockerDaemon", reflect.TypeOf((*MockClient)(nil).StartDockerDaemon))
}

// WaitForDockerDaemon mocks base method
func (m *MockClient) WaitForDockerDaemon() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "WaitForDockerDaemon")
}

// WaitForDockerDaemon indicates an expected call of WaitForDockerDaemon
func (mr *MockClientMockRecorder) WaitForDockerDaemon() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WaitForDockerDaemon", reflect.TypeOf((*MockClient)(nil).WaitForDockerDaemon))
}

// CreateDockerClient mocks base method
func (m *MockClient) CreateDockerClient() (*dockerclient.Client, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateDockerClient")
	ret0, _ := ret[0].(*dockerclient.Client)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateDockerClient indicates an expected call of CreateDockerClient
func (mr *MockClientMockRecorder) CreateDockerClient() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateDockerClient", reflect.TypeOf((*MockClient)(nil).CreateDockerClient))
}

// CreateNetworks mocks base method
func (m *MockClient) CreateNetworks(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateNetworks", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateNetworks indicates an expected call of CreateNetworks
func (mr *MockClientMockRecorder) CreateNetworks(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateNetworks", reflect.TypeOf((*MockClient)(nil).CreateNetworks), ctx)
}

// DeleteNetworks mocks base method
func (m *MockClient) DeleteNetworks(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteNetworks", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteNetworks indicates an expected call of DeleteNetworks
func (mr *MockClientMockRecorder) DeleteNetworks(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteNetworks", reflect.TypeOf((*MockClient)(nil).DeleteNetworks), ctx)
}

// StopAllContainers mocks base method
func (m *MockClient) StopAllContainers() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "StopAllContainers")
}

// StopAllContainers indicates an expected call of StopAllContainers
func (mr *MockClientMockRecorder) StopAllContainers() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StopAllContainers", reflect.TypeOf((*MockClient)(nil).StopAllContainers))
}
