labels:
  app: estafette-ci-builder
  team: estafette-team
  language: golang

pipelines:
  build:
    image: golang:1.8.0-alpine
    workDir: /go/src/github.com/estafette/${ESTAFETTE_LABEL_APP}
    commands:
    - go test ./...
    - CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o ./publish/${ESTAFETTE_LABEL_APP} .

  bake:
    image: docker:17.03.0-ce
    commands:
    - docker info
    - cp Dockerfile ./publish
    - cp dind.sh ./publish
    - docker build -t gcr.io/${ESTAFETTE_GCR_PROJECT}/${ESTAFETTE_LABEL_APP}:${ESTAFETTE_BUILD_VERSION} ./publish
    - ls -latr ./publish
    - rm -rf ./publish

  push-to-gcr-io:
    image: docker:17.03.0-ce
    commands:
    - docker login --email=1234@5678.com --username=_json_key --password='${ESTAFETTE_GCR_PASSWORD}' https://gcr.io
    - docker push gcr.io/${ESTAFETTE_GCR_PROJECT}/${ESTAFETTE_LABEL_APP}:${ESTAFETTE_BUILD_VERSION}