builder:
  track: stable
  medium: memory

labels:
  app-group: estafette-ci
  team: estafette
  language: golang

version:
  semver:
    major: 0
    minor: 0
    releaseBranch: main

stages:
  build:
    image: golang:1.16.0-alpine
    env:
      CGO_ENABLED: 0
      GOOS: linux
      GOARCH: amd64
    commands:
    - go test ./...
    - go build -v -ldflags "-X main.appgroup=${ESTAFETTE_LABEL_APP_GROUP} -X main.app=${ESTAFETTE_GIT_NAME} -X main.version=${ESTAFETTE_BUILD_VERSION} -X main.revision=${ESTAFETTE_GIT_REVISION} -X main.branch=${ESTAFETTE_GIT_BRANCH} -X main.buildDate=${ESTAFETTE_BUILD_DATETIME}" -o ./publish/${ESTAFETTE_GIT_NAME}

  bake-all:
    parallelStages:
      bake:
        image: extensions/docker:dev
        action: build
        no-cache: true
        dontExpand:
        - ESTAFETTE_WORKDIR
        repositories:
        - estafette
        path: ./publish
        copy:
        - templates
        - daemon.json

      bake-gocd-agent:
        image: extensions/docker:dev
        action: build
        no-cache: true
        versionTagSuffix: gocd
        repositories:
        - estafette
        path: ./publish
        copy:
        - templates
        dockerfile: Dockerfile.gocd

  dive-and-trivy-all:
    parallelStages:
      dive:
        image: extensions/docker:dev
        action: dive
        repositories:
        - estafette

      dive-gocd-agent:
        image: extensions/docker:dev
        action: dive
        versionTagSuffix: gocd
        repositories:
        - estafette

      trivy:
        image: extensions/docker:dev
        action: trivy
        repositories:
        - estafette

      trivy-gocd-agent:
        image: extensions/docker:dev
        action: trivy
        versionTagSuffix: gocd
        severity: low
        repositories:
        - estafette

  clean-working-directory:
    image: golang:1.16.0-alpine
    commands:
    - rm -rf ..?* .[!.]* *

  test:
    image: estafette/estafette-ci-builder:${ESTAFETTE_BUILD_VERSION}
    env:
      BUILDER_CONFIG:
        '{
          "action":"build",
          "track":"dev",
          "dockerConfig":{
            "runType":"dind",
            "mtu":1460
          },
          "manifest":{
            "Builder":{
              "Track":"stable",
              "OperatingSystem":"linux"
            },
            "Labels":{
              "app":"estafette-ci-builder",
              "app-group":"estafette-ci",
              "language":"golang",
              "team":"estafette-team"
            },
            "Version":{
              "SemVer":{
                "Major":0,
                "Minor":0,
                "Patch":"{{auto}}",
                "LabelTemplate":"{{branch}}",
                "ReleaseBranch":"master"
              },
              "Custom":null
            },
            "GlobalEnvVars":null,
            "Stages":[
              {
                "Name":"services-test",
                "ContainerImage":"alpine:latest",
                "Shell":"/bin/sh",
                "WorkingDirectory":"/estafette-work",
                "Commands": [
                  "route",
                  "ip addr show eth0",
                  "cat /etc/hosts",
                  "cat /etc/resolv.conf",
                  "apk add curl",
                  "curl -v --connect-timeout 2 --retry 10 --retry-delay 2 --retry-connrefused http://nginx:80/"
                ],
                "When":"status == ''succeeded''",
                "EnvVars":null,
                "AutoInjected":false,
                "Retries":0,
                "Services": [
                  {
                    "Name": "nginx",
                    "ContainerImage": "nginx:alpine",
                    "Shell":"/bin/sh",
                    "When":"status == ''succeeded''",
                    "Readiness": {
                      "Path": "/",
                      "TimeoutSeconds": 30,
                      "Hostname": "nginx",
                      "Port": 80,
                      "Protocol": "http"
                    }
                  },
                  {
                    "Name": "cockroachdb",
                    "ContainerImage": "cockroachdb/cockroach:v19.2.0",
                    "Commands":[
                      "/cockroach/cockroach start-single-node --insecure --advertise-addr cockroachdb"
                    ],
                    "EnvVars":{
                      "COCKROACH_SKIP_ENABLING_DIAGNOSTIC_REPORTING":"true"
                    },
                    "Shell":"/bin/sh",
                    "When":"status == ''succeeded''",
                    "Readiness": {
                      "Path": "/health?ready=1",
                      "TimeoutSeconds": 30,
                      "Hostname": "cockroachdb",
                      "Port": 8080,
                      "Protocol": "http"
                    }
                  }
                ]
              },
              {
                "Name":"git-clone",
                "ContainerImage":"extensions/git-clone:dev",
                "Shell":"/bin/sh",
                "WorkingDirectory":"/estafette-work",
                "Commands":null,
                "shallow": false,
                "When":"status == ''succeeded''",
                "EnvVars":null,
                "AutoInjected":true,
                "Retries":0,
                "CustomProperties":null
              },
              {
                "Name":"parallel-builds",
                "ContainerImage":"",
                "Shell":"/bin/sh",
                "WorkingDirectory":"/estafette-work",
                "Commands":[],
                "When":"status == ''succeeded''",
                "EnvVars":{},
                "AutoInjected":false,
                "Retries":0,
                "CustomProperties":null,
                "ParallelStages":[
                  {
                    "Name":"buildA",
                    "ContainerImage":
                    "golang:1.14.0-alpine3.11",
                    "Shell":"/bin/sh",
                    "WorkingDirectory":"/estafette-work",
                    "Commands":[
                      "go test ./...",
                      "go build -v -ldflags \"-X main.version=${ESTAFETTE_BUILD_VERSION} -X main.revision=${ESTAFETTE_GIT_REVISION} -X main.branch=${ESTAFETTE_GIT_BRANCH} -X main.buildDate=${ESTAFETTE_BUILD_DATETIME}\" -o ./publish/${ESTAFETTE_GIT_NAME}",
                      "echo $PWD",
                      "ls -latr",
                      "ls -latr ./publish"
                    ],
                    "When":"status == ''succeeded''",
                    "EnvVars":{
                      "CGO_ENABLED":"0",
                      "GOOS":"linux",
                      "GOARCH":"amd64"
                    },
                    "AutoInjected":false,
                    "Retries":0,
                    "CustomProperties":null
                  },
                  {
                    "Name":"buildB",
                    "ContainerImage":"alpine:3.10",
                    "Shell":"/bin/sh",
                    "WorkingDirectory":"/estafette-work",
                    "Commands":[
                      "echo hi"
                    ],
                    "When":"status == ''succeeded''"
                  }
                ]
              },
              {
                "Name":"bake-estafette",
                "ContainerImage":"extensions/docker:dev",
                "Shell":"/bin/sh",
                "WorkingDirectory":"/estafette-work",
                "Commands":null,
                "When":"status == ''succeeded''",
                "EnvVars":null,
                "AutoInjected":false,
                "Retries":0,
                "CustomProperties":{
                  "action":"build",
                  "no-cache":true,
                  "tag":"testtag",
                  "expand-variables":false,
                  "path":"./publish",
                  "repositories":["estafette"]
                }
              }
            ],
            "Releases":null
          },
          "jobName":"build-estafette-estafette-ci-builder-391855387650326531",
          "ciServer":{
            "baseUrl":"https://httpstat.us/200",
            "builderEventsUrl":"https://httpstat.us/200",
            "postLogsUrl":"https://httpstat.us/200",
            "jwt":""
          },
          "buildParams":{
            "buildID":391855387650326531
          },
          "git":{
            "repoSource":"github.com",
            "repoOwner":"estafette",
            "repoName":"estafette-ci-builder",
            "repoBranch":"integration-test",
            "repoRevision":"4ba7791566e3f6f69e8542183168ec9b1ad03ca7"
          },
          "buildVersion":{
            "version":"0.0.0-integration-test",
            "major":0,
            "minor":0,
            "patch":"0",
            "autoincrement":0
          },
          "credentials":null,
          "trustedImages":[
            {
              "path":"extensions/docker",
              "runDocker":true
            },
            {
              "path":"estafette/estafette-ci-builder",
              "runPrivileged":true
            },
            {
              "path":"golang",
              "runDocker":true,
              "allowCommands":true
            },
            {
              "path":"extensions/git-clone"
            },
            {
              "path":"bsycorp/kind",
              "runPrivileged":true
            }
          ]
        }'
      SECRET_DECRYPTION_KEY: "8c6E5e7R8ameE2L6qxEcN5Yc3Q7P4Yd4"
      ESTAFETTE_LOG_FORMAT: console

  push-all:
    parallelStages:
      push-to-docker-hub:
        image: extensions/docker:dev
        action: push
        repositories:
        - estafette

      push-gocd-agent-to-docker-hub:
        image: extensions/docker:dev
        action: push
        versionTagSuffix: gocd
        repositories:
        - estafette

  slack-notify:
    image: extensions/slack-build-status:dev
    workspace: estafette
    channels:
    - '#build-status'
    when:
      status == 'succeeded' ||
      status == 'failed'

releases:
  dev:
    triggers:
    - pipeline:
        name: self
        branch: .+
    stages:
      tag-all:
        parallelStages:
          tag-container-image:
            image: extensions/docker:dev
            action: tag
            repositories:
            - estafette
            tags:
            - dev

          tag-gocd-agent-container-image:
            image: extensions/docker:dev
            action: tag
            versionTagSuffix: gocd
            repositories:
            - estafette
            tags:
            - dev-gocd

  beta:
    stages:
      tag-all:
        parallelStages:
          tag-container-image:
            image: extensions/docker:dev
            action: tag
            repositories:
            - estafette
            tags:
            - beta

          tag-gocd-agent-container-image:
            image: extensions/docker:dev
            action: tag
            versionTagSuffix: gocd
            repositories:
            - estafette
            tags:
            - beta-gocd

      slack-notify:
        image: extensions/slack-build-status:dev
        workspace: estafette
        channels:
        - '#build-status'
        when:
          status == 'succeeded' ||
          status == 'failed'

  stable:
    stages:
      tag-all:
        parallelStages:
          tag-container-image:
            image: extensions/docker:dev
            action: tag
            repositories:
            - estafette
            tags:
            - stable
            - latest

          tag-gocd-agent-container-image:
            image: extensions/docker:dev
            action: tag
            versionTagSuffix: gocd
            repositories:
            - estafette
            tags:
            - stable-gocd
            - latest-gocd

      slack-notify:
        image: extensions/slack-build-status:dev
        workspace: estafette
        channels:
        - '#build-status'
        when:
          status == 'succeeded' ||
          status == 'failed'

  nanoserver-1809-dev:
    builder:
      os: windows
      track: nanoserver-1809-stable
    clone: true
    stages:
      build:
        image: estafette/golang:1.16.0-nanoserver-1809
        shell: cmd
        env:
          CGO_ENABLED: 0
          GOOS: windows
          GOARCH: amd64
        commands:
        - go build -v -ldflags "-X main.app=%ESTAFETTE_GIT_NAME% -X main.version=%ESTAFETTE_BUILD_VERSION% -X main.revision=%ESTAFETTE_GIT_REVISION% -X main.branch=%ESTAFETTE_GIT_BRANCH% -X main.buildDate=%ESTAFETTE_BUILD_DATETIME%" -o ./publish/%ESTAFETTE_GIT_NAME%.exe

      bake:
        image: extensions/docker:nanoserver-1809-dev
        action: build
        no-cache: true
        expand-variables: false
        repositories:
        - estafette
        dockerfile: Dockerfile.nanoserver-1809
        path: ./publish
        copy:
        - templates

      push-to-docker-hub:
        image: extensions/docker:nanoserver-1809-dev
        action: push
        repositories:
        - estafette
        tags:
        - nanoserver-1809-dev
        pushVersionTag: false

  nanoserver-1809-beta:
    builder:
      os: windows
      track: nanoserver-1809-dev
    clone: true
    stages:
      build:
        image: estafette/golang:1.16.0-nanoserver-1809
        shell: cmd
        env:
          CGO_ENABLED: 0
          GOOS: windows
          GOARCH: amd64
        commands:
        - go build -v -ldflags "-X main.app=%ESTAFETTE_GIT_NAME% -X main.version=%ESTAFETTE_BUILD_VERSION% -X main.revision=%ESTAFETTE_GIT_REVISION% -X main.branch=%ESTAFETTE_GIT_BRANCH% -X main.buildDate=%ESTAFETTE_BUILD_DATETIME%" -o ./publish/%ESTAFETTE_GIT_NAME%.exe

      bake:
        image: extensions/docker:nanoserver-1809-dev
        action: build
        no-cache: true
        expand-variables: false
        repositories:
        - estafette
        dockerfile: Dockerfile.nanoserver-1809
        path: ./publish
        copy:
        - templates

      push-to-docker-hub:
        image: extensions/docker:nanoserver-1809-dev
        action: push
        repositories:
        - estafette
        tags:
        - nanoserver-1809-beta
        pushVersionTag: false

  nanoserver-1809-stable:
    builder:
      os: windows
      track: nanoserver-1809-stable
    clone: true
    stages:
      build:
        image: estafette/golang:1.16.0-nanoserver-1809
        shell: cmd
        env:
          CGO_ENABLED: 0
          GOOS: windows
          GOARCH: amd64
        commands:
        - go build -v -ldflags "-X main.app=%ESTAFETTE_GIT_NAME% -X main.version=%ESTAFETTE_BUILD_VERSION% -X main.revision=%ESTAFETTE_GIT_REVISION% -X main.branch=%ESTAFETTE_GIT_BRANCH% -X main.buildDate=%ESTAFETTE_BUILD_DATETIME%" -o ./publish/%ESTAFETTE_GIT_NAME%.exe

      bake:
        image: extensions/docker:nanoserver-1809-dev
        action: build
        no-cache: true
        expand-variables: false
        repositories:
        - estafette
        dockerfile: Dockerfile.nanoserver-1809
        path: ./publish
        copy:
        - templates

      push-to-docker-hub:
        image: extensions/docker:nanoserver-1809-dev
        action: push
        repositories:
        - estafette
        tags:
        - nanoserver-1809-stable
        pushVersionTag: false
