labels:
  app: estafette-ci
  team: estafette-team
  language: golang

pipelines:
  build:
    image: golang:1.8.0-alpine
    shell: /bin/sh
    commands:
    - go test -v ./...
    - CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o ./publish/estafette-ci-builder .
