labels:
  app: estafette-ci-builder
  team: estafette-team
  language: golang

pipelines:
  build:
    image: golang:1.8.0-alpine
    workDir: /go/src/github.com/estafette/${ESTAFETTE_LABEL_APP}
    commands:
    - go test `go list ./... | grep -v /vendor/`
    - CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -ldflags "-X main.version=${ESTAFETTE_BUILD_VERSION} -X main.revision=${ESTAFETTE_GIT_REVISION} -X main.branch=${ESTAFETTE_GIT_BRANCH} -X main.buildDate=${ESTAFETTE_BUILD_DATETIME}" -o ./publish/${ESTAFETTE_LABEL_APP} .

  bake:
    image: docker:17.04.0-ce
    commands:
    - cp Dockerfile ./publish
    - docker build -t gcr.io/${ESTAFETTE_GCR_PROJECT}/${ESTAFETTE_LABEL_APP}:${ESTAFETTE_BUILD_VERSION} ./publish

  push-to-gcr-io:
    image: docker:17.04.0-ce
    commands:
    - docker login --username=_json_key --password='${ESTAFETTE_GCR_PASSWORD}' https://gcr.io
    - docker push gcr.io/${ESTAFETTE_GCR_PROJECT}/${ESTAFETTE_LABEL_APP}:${ESTAFETTE_BUILD_VERSION}

  slack-notify:
    image: docker:17.04.0-ce
    commands:
    - | curl -X POST --data-urlencode 'payload={"channel": "#build-status", "username": "estafette-ci-builder", "text": "Build ${ESTAFETTE_BUILD_VERSION} for ${ESTAFETTE_LABEL_APP} has finished successfully!"}' ${ESTAFETTE_SLACK_WEBHOOK}