labels:
  app: estafette-ci-builder
  team: estafette-team
  language: golang

pipelines:
  build:
    image: golang:1.8.0-alpine
    workDir: /go/src/github.com/estafette/${ESTAFETTE_LABEL_APP}
    commands:
    - go test `go list ./... | grep -v /vendor/`
    - CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o ./publish/${ESTAFETTE_LABEL_APP} . -ldflags "-X main.version=${ESTAFETTE_BUILD_VERSION} -X main.revision=`git rev-parse HEAD` -X main.branch=`git rev-parse --abbrev-ref HEAD` -X main.buildDate=`date -u +"%Y-%m-%dT%H:%M:%SZ"`"

  bake:
    image: docker:17.03.0-ce
    commands:
    - cp Dockerfile ./publish
    - docker build -t gcr.io/${ESTAFETTE_GCR_PROJECT}/${ESTAFETTE_LABEL_APP}:${ESTAFETTE_BUILD_VERSION} ./publish

  push-to-gcr-io:
    image: docker:17.03.0-ce
    commands:
    - docker login --username=_json_key --password='${ESTAFETTE_GCR_PASSWORD}' https://gcr.io
    - docker push gcr.io/${ESTAFETTE_GCR_PROJECT}/${ESTAFETTE_LABEL_APP}:${ESTAFETTE_BUILD_VERSION}
