labels:
  app: estafette-ci
  team: estafette-team
  language: golang

pipelines:
  build:
    image: golang:1.8.0-alpine
    shell: /bin/sh
    workingDirectory: /go/src/github.com/estafette/estafette-ci-builder
    commands:
    - go test -v ./...
    - CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o ./publish/estafette-ci-builder .

  bake:
    image: alpine:3.5
    shell: /bin/sh
    commands:
    - cp Dockerfile ./publish
    - docker build -t estafette-ci-builder ./publish