builder:
  track: stable

labels:
  app-group: estafette-ci
  team: estafette-team
  language: golang

version:
  semver:
    major: 0
    minor: 0

stages:
  build:
    image: golang:1.13.0-alpine3.10
    env:
      CGO_ENABLED: 0
      GOOS: linux
      GOARCH: amd64
    commands:
    - go test ./...
    - go build -a -installsuffix cgo -ldflags "-X main.app=${ESTAFETTE_GIT_NAME} -X main.version=${ESTAFETTE_BUILD_VERSION} -X main.revision=${ESTAFETTE_GIT_REVISION} -X main.branch=${ESTAFETTE_GIT_BRANCH} -X main.buildDate=${ESTAFETTE_BUILD_DATETIME}" -o ./publish/${ESTAFETTE_GIT_NAME} .

  bake:
    image: extensions/docker:dev
    action: build
    no-cache: true
    expand-variables: false
    repositories:
    - estafette
    path: ./publish

  bake-gocd-agent:
    image: extensions/docker:dev
    action: build
    no-cache: true
    expand-variables: false
    repositories:
    - estafette.secret(ugcaPF_CdqMZsxsh.4ZumU_A0ufxsjV3MPInyc1VjATZgX9hcB2KQM1KDIOQs)
    path: ./publish
    dockerfile: Dockerfile.gocd

  clean-working-directory:
    image: golang:1.13.0-alpine3.10
    commands:
    - rm -rf ..?* .[!.]* *

  test:
    image: estafette/estafette-ci-builder:${ESTAFETTE_BUILD_VERSION}
    env:
      BUILDER_CONFIG:
        '{
          "action":"build",
          "track":"dev",
          "manifest":{
            "Builder":{
              "Track":"stable"
            },
            "Labels":{
              "app":"estafette-ci-builder",
              "app-group":"estafette-ci",
              "language":"golang",
              "team":"estafette-team"
            },
            "Version":{
              "SemVer":{
                "Major":0,
                "Minor":0,
                "Patch":"{{auto}}",
                "LabelTemplate":"{{branch}}",
                "ReleaseBranch":"master"
              },
              "Custom":null
            },
            "GlobalEnvVars":null,
            "Pipelines":[
              {
                "Name":"git-clone",
                "ContainerImage":"extensions/git-clone:dev",
                "Shell":"/bin/sh",
                "WorkingDirectory":"/estafette-work",
                "Commands":null,
                "shallow": false,
                "When":"status == ''succeeded''",
                "EnvVars":null,
                "AutoInjected":true,
                "Retries":0,
                "CustomProperties":null
              },
              {
                "Name":"build",
                "ContainerImage":
                "golang:1.12.5-alpine3.9",
                "Shell":"/bin/sh",
                "WorkingDirectory":"/go/src/github.com/estafette/${ESTAFETTE_GIT_NAME}",
                "Commands":[
                  "go test `go list ./... | grep -v /vendor/`",
                  "go build -a -installsuffix cgo -ldflags \"-X main.version=${ESTAFETTE_BUILD_VERSION} -X main.revision=${ESTAFETTE_GIT_REVISION} -X main.branch=${ESTAFETTE_GIT_BRANCH} -X main.buildDate=${ESTAFETTE_BUILD_DATETIME}\" -o ./publish/${ESTAFETTE_GIT_NAME} ."
                ],
                "When":"status == ''succeeded''",
                "EnvVars":{
                  "CGO_ENABLED":"0",
                  "GOOS":"linux"
                },
                "AutoInjected":false,
                "Retries":0,
                "CustomProperties":null
              },
              {
                "Name":"bake-estafette",
                "ContainerImage":"extensions/docker:dev",
                "Shell":"/bin/sh",
                "WorkingDirectory":"/estafette-work",
                "Commands":null,
                "When":"status == ''succeeded''",
                "EnvVars":null,
                "AutoInjected":false,
                "Retries":0,
                "CustomProperties":{
                  "action":"build",
                  "copy":[
                    "Dockerfile"
                  ],
                  "path":"./publish",
                  "repositories":["estafette"]
                }
              }
            ],
            "Releases":null
          },
          "jobName":"build-estafette-estafette-ci-builder-391855387650326531",
          "ciServer":{
            "baseUrl":"https://httpstat.us/200",
            "builderEventsUrl":"https://httpstat.us/200",
            "postLogsUrl":"https://httpstat.us/200",
            "apiKey":""
          },
          "buildParams":{
            "buildID":391855387650326531
          },
          "git":{
            "repoSource":"github.com",
            "repoOwner":"estafette",
            "repoName":"estafette-ci-builder",
            "repoBranch":"integration-test",
            "repoRevision":"f394515b2a91ea69addf42e4b722442b2905e268"
          },
          "buildVersion":{
            "version":"0.0.0-integration-test",
            "major":0,
            "minor":0,
            "patch":"0",
            "autoincrement":0
          },
          "credentials":null,
          "trustedImages":[
            {
              "path":"extensions/docker",
              "runDocker":true
            },
            {
              "path":"estafette/estafette-ci-builder",
              "runPrivileged":true
            },
            {
              "path":"golang",
              "runDocker":true,
              "allowCommands":true
            },
            {
              "path":"extensions/git-clone"
            }
          ]
        }'
      SECRET_DECRYPTION_KEY: "8c6E5e7R8ameE2L6qxEcN5Yc3Q7P4Yd4"

  push-to-docker-hub:
    image: extensions/docker:dev
    action: push
    repositories:
    - estafette

  push-to-gcr-io:
    image: extensions/docker:dev
    action: push
    repositories:
    - estafette.secret(ugcaPF_CdqMZsxsh.4ZumU_A0ufxsjV3MPInyc1VjATZgX9hcB2KQM1KDIOQs)

  slack-notify:
    image: extensions/slack-build-status:dev
    workspace: estafette
    channels:
    - '#build-status'
    when:
      status == 'succeeded' ||
      status == 'failed'

releases:
  dev:
    triggers:
    - pipeline:
        name: self
        branch: .+
    stages:
      tag-container-image:
        image: extensions/docker:dev
        action: tag
        repositories:
        - estafette
        tags:
        - dev

      tag-gcr-io-image:
        image: extensions/docker:dev
        action: tag
        repositories:
        - estafette.secret(ugcaPF_CdqMZsxsh.4ZumU_A0ufxsjV3MPInyc1VjATZgX9hcB2KQM1KDIOQs)
        tags:
        - dev

  beta:
    stages:
      tag-container-image:
        image: extensions/docker:dev
        action: tag
        repositories:
        - estafette
        tags:
        - beta

      tag-gcr-io-image:
        image: extensions/docker:dev
        action: tag
        repositories:
        - estafette.secret(ugcaPF_CdqMZsxsh.4ZumU_A0ufxsjV3MPInyc1VjATZgX9hcB2KQM1KDIOQs)
        tags:
        - beta

      slack-notify:
        image: extensions/slack-build-status:dev
        workspace: estafette
        channels:
        - '#build-status'
        when:
          status == 'succeeded' ||
          status == 'failed'

  stable:
    stages:
      tag-container-image:
        image: extensions/docker:dev
        action: tag
        repositories:
        - estafette
        tags:
        - stable
        - latest

      tag-gcr-io-image:
        image: extensions/docker:dev
        action: tag
        repositories:
        - estafette.secret(ugcaPF_CdqMZsxsh.4ZumU_A0ufxsjV3MPInyc1VjATZgX9hcB2KQM1KDIOQs)
        tags:
        - stable
        - latest

      slack-notify:
        image: extensions/slack-build-status:dev
        workspace: estafette
        channels:
        - '#build-status'
        when:
          status == 'succeeded' ||
          status == 'failed'