labels:
  app: estafette-ci-builder
  team: estafette-team
  language: golang

pipelines:
  build:
    image: golang:1.8.0-alpine
    workDir: /go/src/github.com/estafette/${ESTAFETTE_LABEL_APP}
    commands:
    - go test ./...
    - CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o ./publish/${ESTAFETTE_LABEL_APP} .

  bake:
    image: docker:17.03.0-ce
    commands:
    - cp Dockerfile ./publish
    - docker build -t gcr.io/estafette/${ESTAFETTE_LABEL_APP}:${ESTAFETTE_BUILD_VERSION} ./publish
    - ls -latr ./publish
    - rm -rf ./publish

  push-to-docker-hub:
    image: docker:17.03.0-ce
    commands:
    - docker login --username='${ESTAFETTE_DOCKER_HUB_USERNAME}' --pasword='${ESTAFETTE_DOCKER_HUB_PASSWORD}'
    - docker push estafette/${ESTAFETTE_LABEL_APP}:${ESTAFETTE_BUILD_VERSION}