FROM golang:1.13.0-nanoserver-1809 as builder

ENV CGO_ENABLED=0 \
    GOOS=windows \
    GOARCH=amd64

COPY . C:/build

WORKDIR C:/build

RUN go build

FROM mcr.microsoft.com/windows/nanoserver:1809

COPY --from=builder C:/build/estafette-ci-builder.exe c:/estafette-ci-builder.exe

ENV ESTAFETTE_CI_SERVER="estafette" \
    ESTAFETTE_WORKDIR="C:/estafette-work"

WORKDIR ${ESTAFETTE_WORKDIR}

ENTRYPOINT ["C:/estafette-ci-builder.exe"]