FROM travix/gocd-agent:20.3.0-alpine

MAINTAINER estafette.io

LABEL maintainer="estafette.io" \
      description="The ${ESTAFETTE_GIT_NAME} is the component that runs builds as defined in the .estafette.yaml manifest"

RUN mkdir -p /estafette-entrypoints \
    && docker version || true

# copy builder
COPY ${ESTAFETTE_GIT_NAME} /usr/bin/
COPY templates /entrypoint-templates

ENV ESTAFETTE_CI_SERVER="gocd" \
    DOCKER_API_VERSION="1.38" \
    ESTAFETTE_LOG_FORMAT="console"