labels:
  app: estafette-ci-builder
  team: estafette-team
  language: golang

pipelines:
  build:
    image: golang:1.8.0-alpine
    workDir: /go/src/github.com/estafette/estafette-ci-builder
    commands:
    - go test -v ./...
    - CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o ./publish/estafette-ci-builder .

  bake:
    image: docker:17.03.0-ce
    shell: /bin/bash
    commands:
    - cp Dockerfile ./publish
    - docker build -t estafette-ci-builder ./publish
    when:
      branch == 'master'